In [2]:
import torch 
import math 
div_term = (torch.arange(0, 10, 2).float() * -(math.log(10000.0) / 10)).exp()

In [3]:
div_term

tensor([1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04])

In [ ]:
10000

In [9]:
1/torch.pow(10000,torch.arange(0,10,2).float()/10)

tensor([1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04])

In [10]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])